# Generated by Django 4.2.7 on 2023-11-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('immatricule', models.CharField(max_length=50)),
                ('categorie', models.CharField(max_length=50)),
                ('affectation', models.CharField(max_length=100, null=True)),
                ('date_achat', models.DateField(null=True)),
                ('date_mise_en_service', models.DateField(null=True)),
            ],
            options={
                'verbose_name': 'Vehicule',
                'verbose_name_plural': 'Vehicules',
                'db_table': 'carburant_vehicule',
            },
        ),
    ]
