# Generated by Django 4.2.7 on 2023-11-25 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carburant', '0002_alter_vehicule_date_achat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicule',
            name='date_achat',
        ),
        migrations.RemoveField(
            model_name='vehicule',
            name='date_mise_en_service',
        ),
    ]
