# Generated by Django 4.2.7 on 2023-11-25 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carburant', '0003_remove_vehicule_date_achat_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='vehicule',
            table=None,
        ),
    ]
