# Generated by Django 4.2.7 on 2023-12-07 15:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carburant', '0005_cuve_ravitaillement_cuve_vehicules'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rajout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure_rajout', models.DateTimeField()),
                ('quantiteRajout', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cuve', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carburant.cuve')),
            ],
            options={
                'verbose_name': 'Rajout',
                'verbose_name_plural': 'Rajouts',
            },
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('adresse', models.CharField(max_length=40)),
                ('cuves', models.ManyToManyField(related_name='mestations', through='carburant.Rajout', to='carburant.cuve')),
            ],
            options={
                'verbose_name': 'Station',
                'verbose_name_plural': 'Stations',
            },
        ),
        migrations.AddField(
            model_name='rajout',
            name='station',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carburant.station'),
        ),
    ]
