# Generated by Django 4.2.7 on 2023-12-07 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carburant', '0006_rajout_station_rajout_station'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rajout',
            old_name='quantiteRajout',
            new_name='quantite_rajout',
        ),
    ]
