# Generated by Django 4.2.7 on 2023-12-07 17:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carburant', '0007_rename_quantiterajout_rajout_quantite_rajout'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Ravitaillement',
            new_name='RavitaillementCuve',
        ),
        migrations.AlterModelOptions(
            name='ravitaillementcuve',
            options={'verbose_name': 'RavitaillementCuves', 'verbose_name_plural': 'RavitaillementCuves'},
        ),
        migrations.RemoveField(
            model_name='cuve',
            name='vehicules',
        ),
        migrations.AddField(
            model_name='vehicule',
            name='cuves',
            field=models.ManyToManyField(related_name='vehicules_ravitaille_cuves', through='carburant.RavitaillementCuve', to='carburant.cuve'),
        ),
        migrations.AlterField(
            model_name='station',
            name='cuves',
            field=models.ManyToManyField(related_name='station_rajout', through='carburant.Rajout', to='carburant.cuve'),
        ),
        migrations.CreateModel(
            name='RavitaillementStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_heure_ravitaillement', models.DateTimeField()),
                ('quantite', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carburant.station')),
                ('vehicule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carburant.vehicule')),
            ],
            options={
                'verbose_name': 'RavitaillementStations',
                'verbose_name_plural': 'RavitaillementStations',
            },
        ),
        migrations.AddField(
            model_name='vehicule',
            name='stations',
            field=models.ManyToManyField(related_name='vehicules_ravitaille_station', through='carburant.RavitaillementStation', to='carburant.station'),
        ),
    ]
