# Generated by Django 4.2.7 on 2023-12-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connexion', '0004_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profile/Default.jpeg', null=True, upload_to='profile/'),
        ),
    ]
